# Generated by Django 3.1.3 on 2022-06-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0002_routine_detial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routine_detial',
            new_name='Routine_detail',
        ),
    ]
