# Generated by Django 3.1.3 on 2022-07-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0004_routine_modelkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('modelkey', models.CharField(max_length=10)),
            ],
        ),
    ]
